### ISSUE TITLE
Important!!!

### ISSUE THREAD

**Issue by xujialiu** [luhaifeng666/obsidian-doc#5]
作者你好! 请你关闭这个仓库, 因为下面这两个文件似乎泄露了你的个人隐私!!!

Users/mrblacklu/文档/obsidian_notes/同程/备忘.md
Users/mrblacklu/文档/obsidian_notes/备忘.md

请关闭这个仓库, 并修改泄露的密码, 防止别有用心之人, 谢谢!

**Comment by luhaifeng666** [comment]
这个仓库是我用来同步笔记用的，已经删掉了部分风险文件。感谢提醒~

**Comment by xujialiu** [comment]
![image](https://github.com/luhaifeng666/obsidian-doc/assets/46064313/93de0bf7-6d9d-44bd-ab62-f38911011935)

GIt并不能完全删除文件, 仍然可以从.git的提取[文件差异](https://github.com/luhaifeng666/obsidian-doc/compare/fcf21907fda9ce5470dc9a88687d2d383906c7a0...f38ec36cf730911232599e5028c84999cfa3bd0f), 还是希望能关闭这个仓库, 重新新建一个新的, 彻底防止信息泄露的风险
